[project]
name = "fast-f1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastf1>=3.5.3",
    "streamlit>=1.46.0",
]
